server.port=8081
spring.application.name=Architecture-basice


# H2 Config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# bật quản lý Web Console
spring.h2.console.enabled=true


# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop


# in console (nếu cần)
#logging.level.com.zaxxer.hikari=DEBUG
#logging.level.org.springframework.jdbc=DEBUG


# nếu dùng file jsp (hiện tại con vẫn để)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp